name: Validate Pull Request

on:
  workflow_dispatch:
  pull_request:


jobs:
  gen_pkg_source:
    name: Generate package source
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get tags
        run: |
          git fetch --tags origin
          git describe

      - name: Install Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install -r envs/requirements_test.txt
          python -m pip install .
      
      - name: Build with pre and post validation
        run: |
          python tools/build_package/build_with_checks.py
