name: Validate Pull Request

on:
  workflow_dispatch:
  pull_request:

jobs:
  gen_pkg_source:
    name: Generate package source
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get tags
        run: |
          git fetch --tags origin
          git describe

      - name: Install Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install -r envs/requirements_test.txt
          python -m pip install .

      - name: Get changed folders in the contrib folder
        id: changed-contribs
        uses: tj-actions/changed-files@v35
        with:
          files: contrib/*/  # Alternatively using: `docs/**` or `docs`

      - name: List all changed contributions
        run: |
          for folder in ${{ steps.changed-contribs.outputs.all_changed_files }}; do
            contrib_name=$(echo $folder | cut -d'/' -f2)
            echo $contrib_name >> changed_contribs.txt
          done
          cat changed_contribs.txt

      - name: Build with pre and post validation
        run: |
          python espresso_machine/build_package/build.py --pre --post -f changed_contribs.txt

  build_wheels_non_windows:
    if: github.repository_owner == 'inlab-geo'
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # Giving up windows, see the following two links:
        # https://groups.google.com/g/comp.lang.fortran/c/Jna-QAHCOpk/m/VZq7gVq3AgAJ
        # https://github.com/awvwgk/setup-fortran/issues/6
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get tags
        run: |
          git fetch --tags origin
          git describe

      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      
      - name: Setup GNU Fortran
        uses: modflowpy/install-gfortran-action@v1

      - name: Prepare Python environment
        run: |
          python -m pip install -r envs/requirements_test.txt
          python -m pip install .

      - name: Get changed folders in the contrib folder
        id: changed-contribs
        uses: tj-actions/changed-files@v35
        with:
          files: contrib/*/

      - name: List all changed contributions
        run: |
          for folder in ${{ steps.changed-contribs.outputs.all_changed_files }}; do
            contrib_name=$(echo $folder | cut -d'/' -f2)
            echo $contrib_name >> changed_contribs.txt
          done

      - name: Generate package source with contributions
        run: |
          python espresso_machine/build_package/build.py -f changed_contribs.txt

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        working-directory: _esp_build
        env:
          CIBW_SKIP: pp* cp36* *-win32 *-manylinux_i686 *-musllinux_*
          CIBW_ARCHS_MACOS: universal2      # to reduce testing time
          CIBW_REPAIR_WHEEL_COMMAND_MACOS: ""
