name: Upload to PyPI

on:
  workflow_dispatch:
  push:
    branches: main
    paths:
      - "src/cofi_espresso/version.py"

jobs:
  tag_and_gen_pkg_source:
    if: github.repository_owner == 'inlab-geo'
    name: Tag current commit and send package source to _esp_build branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      
      - name: Extract Release Version
        id: release_version
        working-directory: src/cofi_espresso
        run: |
          set -e
          python -c "import version as v; print(v.__version__)"
          echo ::set-output name=version::$(python -c "import version as v; print(v.__version__)")

      - name: Create release tag
        uses: rickstaa/action-create-tag@v1.3.0
        with:
          tag: "v${{ steps.release_version.outputs.version }}"
          force_push_tag: true

      - name: Install dependencies
        run: |
          python -m pip install -r envs/requirements_test.txt

      - name: Build with pre and post validation
        run: |
          python -m pip install .
          python tools/build_package/build_with_checks.py

      - name: Deploy to esp_build branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: esp_build
          FOLDER: _esp_build
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

  tag_pkg_source:
    name: Tag package source
    needs: tag_and_gen_pkg_source
    runs-on: ubuntu-latest
    steps:
      - name: Checkout build branch
        uses: actions/checkout@v3
        with:
          ref: esp_build

      - name: Extract Release Version
        id: release_version
        working-directory: src/cofi_espresso
        run: |
          set -e
          python -c "import version as v; print(v.__version__)"
          echo ::set-output name=version::$(python -c "import version as v; print(v.__version__)")

      - name: Create release build tag
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git tag "v${{ steps.release_version.outputs.version }}-build"
          git push origin "v${{ steps.release_version.outputs.version }}-build"

  publish_pypi:
    name: Build source distribution and upload to PyPI
    needs: tag_and_gen_pkg_source
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: esp_build

      - name: Install Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Set up environment
        run: |
          python -m pip install scikit-build versioningit

      - name: Build and check sdist
        run: |
          pip install build
          python -m build --sdist --wheel

      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@v1.4.1
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
          verbose: true

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@v1.4.1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
          verbose: true
